name: Publish VS Code Extension

on:
  push:
    tags:
      - "v*" # Trigger on version tags like v0.2.0
  workflow_dispatch: # Allow manual triggering

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci # Use npm ci for faster installs in CI environments

      - name: Run Tests, Lint, and Compile
        run: npm test # This runs pretest (compile, lint) and then tests

      - name: Package Extension
        run: npm run package # Creates the .vsix file in artifacts/

      # @todo: Add a step here to verify CHANGELOG.md changes if needed
      # - name: Check Changelog
      #   run: |
      #     # Add script/command to check if CHANGELOG.md was updated for the release tag
      #     echo "Implement Changelog check here"

      - name: Publish to Visual Studio Marketplace
        if: startsWith(github.ref, 'refs/tags/v') # Only publish on version tags
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          # Access Token stored in GitHub Secrets
          pat: ${{ secrets.VSCE_PAT }}
          packagePath: "artifacts" # Directory where the .vsix file is located

      - name: Upload VSIX Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vsix-package
          path: artifacts/*.vsix # Upload the generated .vsix file
